# Generated by Django 2.2.4 on 2019-08-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='askimage/')),
                ('body', models.TextField()),
                ('subject', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CodeShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shareimage/')),
                ('body', models.TextField()),
                ('subject', models.CharField(max_length=50)),
                ('university', models.CharField(default='해당 없음', max_length=50)),
                ('score', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=50)),
            ],
        ),
    ]
