# Generated by Django 2.2.4 on 2019-08-03 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeask',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='codeshare',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
