# Generated by Django 2.2.4 on 2019-08-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbookapp', '0002_auto_20190803_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeshare',
            name='score',
            field=models.CharField(default='없음', max_length=50),
        ),
        migrations.AlterField(
            model_name='codeshare',
            name='university',
            field=models.CharField(default='없음', max_length=50),
        ),
    ]
