# Generated by Django 2.2.4 on 2019-08-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbookapp', '0003_auto_20190803_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeask',
            name='codes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codeshare',
            name='codes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
