# Generated by Django 2.2.4 on 2019-08-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbookapp', '0004_auto_20190803_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeask',
            name='codes',
            field=models.TextField(default='코드 없음'),
        ),
        migrations.AlterField(
            model_name='codeshare',
            name='codes',
            field=models.TextField(default='코드 없음'),
        ),
    ]
