# Generated by Django 2.2.4 on 2019-08-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbookapp', '0005_auto_20190803_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharecontents', models.CharField(max_length=200)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharecomments', to='cbookapp.CodeShare')),
            ],
        ),
        migrations.CreateModel(
            name='ShareRe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resharecontents', models.CharField(max_length=200)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharereplies', to='cbookapp.ShareComment')),
            ],
        ),
    ]
