# Generated by Django 2.2.4 on 2019-08-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbookapp', '0006_sharecomment_sharere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharecomment',
            options={'ordering': ['id']},
        ),
    ]
